apiVersion: argoproj.skyscanner.net/v1alpha1
kind: ProgressiveSync
metadata:
  labels:
    argocd.argoproj.io/instance: goinfra
  name: goinfra
  namespace: argocd
spec:
  sourceRef:
    apiGroup: argoproj.io/v1alpha1
    kind: ApplicationSet
    name: appset-goinfra
  stages:
    - maxParallel: 1
      maxTargets: 1
      name: one cell as canary in eu-west-1
      targets:
        clusters:
          selector:
            matchLabels:
              region: eu-west-1
    - maxParallel: 2
      maxTargets: 100%
      name: rollout to remaining cells in every other region
      targets:
        clusters:
          selector:
            matchExpressions:
              - key: region
                operator: NotIn
                values:
                  - eu-west-1
