apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      volumes:
        - name: prc-config
          secret:
            secretName: prc-config
      containers:
      - command:
        - ./start.sh
        args:
        - --enable-leader-election
        image: controller:latest
        # TODO: Kustomize this based on env
        ports:
        - containerPort: 2345
          name: delve-dbg-port
        # imagePullPolicy: Never
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
            - mountPath: /etc/prcconfig
              name: prc-config
              readOnly: true
      terminationGracePeriodSeconds: 10
