apiVersion: v1
kind: Secret
metadata:
  name: prc-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ARGOCD_AUTH_TOKEN: {{ .Values.configSecret.argoCDAuthToken | b64enc }}
  ARGOCD_SERVER_ADDR: {{ .Values.configSecret.argoCDServerAddr | b64enc }}
  ARGOCD_INSECURE: {{ .Values.configSecret.argoCDInsecure | b64enc }}
