{{- if not .Values.configSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-progressive-rollout.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  {{- with .Values.configSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  ARGOCD_AUTH_TOKEN: {{ .Values.config.argoCDAuthToken | b64enc }}
  ARGOCD_SERVER_ADDR: {{ .Values.config.argoCDServerAddr | b64enc }}
  ARGOCD_INSECURE: {{ .Values.config.argoCDInsecure | b64enc }}
{{- end }}
