{{- if not .Values.configSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: prc-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ARGOCD_AUTH_TOKEN: {{ .Values.config.argoCDAuthToken | b64enc }}
  ARGOCD_SERVER_ADDR: {{ .Values.config.argoCDServerAddr | b64enc }}
  ARGOCD_INSECURE: {{ .Values.config.argoCDInsecure | b64enc }}
{{- end }}
