# permissions for end users to view progressiverollouts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: progressiverollout-viewer-role
rules:
- apiGroups:
  - deployment.skyscanner.net
  resources:
  - progressiverollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployment.skyscanner.net
  resources:
  - progressiverollouts/status
  verbs:
  - get
