# permissions for end users to view progressivesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: progressivesync-viewer-role
rules:
- apiGroups:
  - argoproj.skyscanner.net
  resources:
  - progressivesyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.skyscanner.net
  resources:
  - progressivesyncs/status
  verbs:
  - get
