# permissions for end users to edit progressivesyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: progressiverollout-editor-role
rules:
- apiGroups:
  - argoproj.skyscanner.net
  resources:
  - progressivesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.skyscanner.net
  resources:
  - progressivesyncs/status
  verbs:
  - get
