
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployment.skyscanner.net
  resources:
  - progressiverollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployment.skyscanner.net
  resources:
  - progressiverollouts/status
  verbs:
  - get
  - patch
  - update
