apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "applicationset-progressive-sync.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "applicationset-progressive-sync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "applicationset-progressive-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "applicationset-progressive-sync.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        {{- if .Values.configSecret.name }}
        - name: {{ .Values.configSecret.name }}
        {{- else }}
        - name: {{ include "applicationset-progressive-sync.fullname" . }}-config
        {{- end }}
          secret:
            {{- if .Values.configSecret.name }}
            secretName: {{ .Values.configSecret.name }}
            {{- else }}
            secretName: {{ include "applicationset-progressive-sync.fullname" . }}-config
            {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "applicationset-progressive-sync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - /manager
            - --metrics-addr={{ .Values.args.metricsAddr }}
            {{- if or (gt ( .Values.replicaCount | int64) 1) .Values.args.enableLeaderElection }}
            - --enable-leader-election=true
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-metrics
              containerPort: {{ (split ":" .Values.args.metricsAddr)._1 }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/prcconfig
              {{- if .Values.configSecret.name }}
              name: {{ .Values.configSecret.name }}
              {{- else }}
              name: {{ include "applicationset-progressive-sync.fullname" . }}-config
              {{- end }}
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
