name: CodeQL

on:
  pull_request:
  schedule:
    - cron: '20 17 * * 1'

jobs:
  codeql:
    name: codeql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Build
        run: make build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
